[build]
  command = "npm run build"
  publish = ".next"

[functions]
  directory = "netlify/functions"

[functions."fetch-scores-cron"]
  timeout = 120

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
